package com.techbeloved.churchbeloved.data.model;

import java.util.Date;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import static androidx.room.ForeignKey.CASCADE;

@Entity(tableName = "videos", indices = @Index(value = {"id", "title", "artist"}),
        foreignKeys = @ForeignKey(entity = Sermon.class, parentColumns = "id",
                childColumns = "sermon_id", onDelete = CASCADE))
public class Video {

    /**
     * The id autogenerated by Firebase
     */
    @PrimaryKey
    @NonNull
    private String id;
    private String title;

    @ColumnInfo(name = "sermon_id")
    private String sermonId;

    /**
     * The location of the video (Youtube, Vimeo, etc)
     */
    private String location;

    /**
     * The stream Id can be used to construct the stream url
     */
    private String streamId;

    private Date dowloaded;

    public Video() {}

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getStreamId() {
        return streamId;
    }

    public void setStreamId(String streamId) {
        this.streamId = streamId;
    }

    public String getSermonId() {
        return sermonId;
    }

    public void setSermonId(String sermonId) {
        this.sermonId = sermonId;
    }

    public Date getDowloaded() {
        return dowloaded;
    }

    public void setDowloaded(Date dowloaded) {
        this.dowloaded = dowloaded;
    }
}
